#installing Docker and Kubernetes inside docker
FROM jenkins/jenkins:lts

USER root

# Installer Docker + curl
RUN apt-get update && \
    apt-get install -y docker.io curl && \
    apt-get clean

# Installer kubectl
RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    rm kubectl

USER jenkins